import { readdirSync } from "node:fs";
import { basename, extname, join } from "node:path";

/**
 * Auto-generate API documentation from route files.
 *
 * Scans src/api/ directory and generates an OpenAPI-like JSON spec.
 * Next.js has no built-in equivalent — you need swagger-jsdoc etc.
 *
 * Usage:
 *   import { generateAPIDocs } from "virexjs";
 *   const docs = generateAPIDocs("src/api");
 *
 *   // Or serve at /api/docs:
 *   export const GET = defineAPIRoute(() => json(docs));
 */

export interface APIEndpoint {
	path: string;
	methods: string[];
	file: string;
}

export interface APIDocs {
	title: string;
	version: string;
	baseUrl: string;
	endpoints: APIEndpoint[];
	generatedAt: string;
}

/**
 * Scan API directory and generate documentation.
 */
export function generateAPIDocs(
	apiDir: string,
	options?: { title?: string; version?: string; baseUrl?: string },
): APIDocs {
	const { title = "VirexJS API", version = "0.1.0", baseUrl = "/api" } = options ?? {};
	const endpoints: APIEndpoint[] = [];

	scanAPIDir(apiDir, baseUrl, endpoints);

	return {
		title,
		version,
		baseUrl,
		endpoints: endpoints.sort((a, b) => a.path.localeCompare(b.path)),
		generatedAt: new Date().toISOString(),
	};
}

function scanAPIDir(dir: string, basePath: string, endpoints: APIEndpoint[]): void {
	let entries: string[];
	try {
		entries = readdirSync(dir);
	} catch {
		return;
	}

	for (const entry of entries) {
		const fullPath = join(dir, entry);
		const ext = extname(entry);

		if (ext === ".ts" || ext === ".tsx") {
			const name = basename(entry, ext);
			const routePath = name === "index" ? basePath : `${basePath}/${name}`;

			// Detect HTTP methods by checking exports
			const methods = detectMethods(fullPath);
			if (methods.length > 0) {
				endpoints.push({ path: routePath, methods, file: entry });
			}
		}
	}
}

const VALID_METHODS = new Set(["GET", "POST", "PUT", "DELETE", "PATCH"]);

function detectMethods(filePath: string): string[] {
	try {
		const { readFileSync } = require("node:fs");
		const content = readFileSync(filePath, "utf-8");
		const methods: string[] = [];
		for (const method of VALID_METHODS) {
			// Check for "export const GET" or "export function GET" patterns
			if (
				content.includes(`export const ${method}`) ||
				content.includes(`export function ${method}`)
			) {
				methods.push(method);
			}
		}
		return methods;
	} catch {
		return [];
	}
}

/**
 * Render API docs as HTML page.
 */
export function renderAPIDocsHTML(docs: APIDocs): string {
	const methodColors: Record<string, string> = {
		GET: "#22c55e",
		POST: "#3b82f6",
		PUT: "#f59e0b",
		DELETE: "#ef4444",
		PATCH: "#a855f7",
	};

	const endpointRows = docs.endpoints
		.flatMap((ep) =>
			ep.methods.map(
				(method) =>
					`<tr>
					<td style="padding:10px 16px"><span style="display:inline-block;padding:2px 10px;border-radius:4px;font-size:12px;font-weight:700;color:#fff;background:${methodColors[method] ?? "#666"}">${method}</span></td>
					<td style="padding:10px 16px;font-family:monospace;font-size:14px">${ep.path}</td>
					<td style="padding:10px 16px;color:#9ca3af;font-size:13px">${ep.file}</td>
				</tr>`,
			),
		)
		.join("\n");

	return `<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>${docs.title}</title>
	<style>
		* { box-sizing: border-box; margin: 0; }
		body { font-family: system-ui, sans-serif; color: #111; background: #fff; padding: 32px; }
		h1 { font-size: 24px; margin-bottom: 4px; }
		p { color: #6b7280; margin-bottom: 24px; }
		table { width: 100%; border-collapse: collapse; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden; }
		thead { background: #f9fafb; }
		th { text-align: left; padding: 10px 16px; font-size: 13px; color: #374151; border-bottom: 1px solid #e5e7eb; }
		tr:not(:last-child) td { border-bottom: 1px solid #f3f4f6; }
		code { background: #f3f4f6; padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }
	</style>
</head>
<body>
	<h1>${docs.title}</h1>
	<p>v${docs.version} — ${docs.endpoints.length} endpoints — Generated ${docs.generatedAt.split("T")[0]}</p>
	<table>
		<thead><tr><th>Method</th><th>Path</th><th>File</th></tr></thead>
		<tbody>${endpointRows}</tbody>
	</table>
	<p style="margin-top:16px;font-size:12px;color:#d1d5db">Auto-generated by VirexJS</p>
</body>
</html>`;
}
